### ISSUE TITLE
Datepicker: design issue when no label in IE11 and Edge

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1864]
Unfortunately IE11 and Edge still exist, and the Datepicker renders extra space when there's no `label` attr provided, which breaks our design...

See screenshot from offic Storybook.

Possible workaround:

```css
axa-datepicker article.m-datepicker {
  display: block; // override "display: inline" which causes problem in IE11+Edge
}
```

Question:

why does this css declaration exists in Datepicker's scss file? What is its purpose?
![image](https://user-images.githubusercontent.com/43809369/86921462-78a42800-c12b-11ea-9827-8b31b2284580.png)

**Screenshot:**

![image](https://user-images.githubusercontent.com/43809369/86921518-8a85cb00-c12b-11ea-98d4-96bbebbc65fa.png)
