### ISSUE TITLE
Stylelint config new-line-before keyword related code missing

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#545]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

I expect that different SCSS/CSS syntax is separated by newlines, like `@at-rules`, `declarations: value;`, `.selectors`, etc.

**Good:**

```css
.foo {
  @at-rule no-block();
  @at-rule no-block();

  display: block;
  text-align: left;

  span {}

  @at-rule with-block() {
     // ...
  }
}
```

**Bad:**

```css
.foo {
  @at-rule no-block();
  @at-rule no-block();
  display: block;
  text-align: left;
  span {}
  @at-rule with-block() {
     // ...
  }
}
```

Issue at [stylelint-order package](https://github.com/hudochenkov/stylelint-order)
https://github.com/hudochenkov/stylelint-order/issues/66

## Actual Behavior

Not producing any errors right now...
